name: Create-Variables
on: push

jobs:
  Create-Variables:
    name: Creating and passing variables
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats JsonTo-Variable
        uses: SecureHats/JsonTo-Variable@v0.0.4
        with:
          filePath: 'variables/env.json'

  Obtain-Variables:
    needs: [Create-Variables]       # <- Jobs run concurrently by default. Over this with the 'needs' keyword to set dependents.
    name: Reading previous variables
    runs-on: ubuntu-latest    
    
    steps:
    #Example 4.5
    - name: Print output variable
      run: |
        Write-Host "Tonights dinner will be"
