name: Create-Variables
on: push

jobs:
  job1:
    name: Creating and passing variables
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.spin_up.outputs.owner }}
      ProductOwner: ${{ steps.spin_up.outputs.Project_ProductOwner }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats JsonTo-Variable
        id: spin_up
        uses: SecureHats/JsonTo-Variable@v0.0.19
        with:
          filePath: 'variables/env.json'
          arraySeparator: ','
          outputs: $true
    
#       - run: |
#           echo "having dinner with ${{ env.Project_ProductOwner }}"
#           echo "also having dinner with ${{ env.owner }}"
#           echo "we are going to have a party with ${{ env.Project_PowerUsers}}"

  job2:
    needs: job1       # <- Jobs run concurrently by default. Over this with the 'needs' keyword to set dependents.
    name: Reading previous variables
    runs-on: ubuntu-latest    
    
    steps:
    #Example 4.5
    - name: Print output variable
      run: |
        echo "having dinner with ${{ needs.job1.outputs.ProductOwner }}"
        echo "also having dinner with ${{ needs.job1.outputs.output1 }}"
        echo "we are going to have a party with ${{ env.Project_PowerUsers}}"
