name: Create-Variables
on: push

jobs:
  Create-Variables:
    name: Creating and passing variables
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats JsonTo-Variable
        uses: SecureHats/JsonTo-Variable@v0.0.15
        with:
          filePath: 'variables/env.json'
          arraySeparator: ','
#       - run: |
#           echo "having dinner with ${{ env.Project_ProductOwner }}"
#           echo "also having dinner with ${{ env.owner }}"
#           echo "we are going to have a party with ${{ env.Project_PowerUsers}}"

  Obtain-Variables:
    needs: [Create-Variables]       # <- Jobs run concurrently by default. Over this with the 'needs' keyword to set dependents.
    name: Reading previous variables
    runs-on: ubuntu-latest    
    
    steps:
    #Example 4.5
    - name: Print output variable
      run: |
        echo "having dinner with ${{ env.Project_ProductOwner }}"
        echo "also having dinner with ${{ env.owner }}"
        echo "we are going to have a party with ${{ env.Project_PowerUsers}}"
